### ISSUE TITLE
How to shard model across multiple gpus/train long sequences?

### ISSUE THREAD

**Issue by hyeh20** [kakaobrain/solvent#2]
Hello, 
Thank you for putting together and posting this code. I am interested in training on my own dataset, but my sequences are all around 800 in length which makes it very expensive in terms of gpu vram. So far, we found that we can fit 2-3 evoformer blocks, but would be interested in scaling up. We would prefer to avoid cropping the sequences to shorter lengths. One approach we were thinking of was sharding the model across our gpus to alleviate the vram use, but we've haven't had much success here. We've tried several sharding methods include isolating out the SSPF model and wrapping it a pytorch lightning wrapper and utilizing deepspeed but we run into issues where the model isn't actually sharding. We suspect these issues may be due to incompatibilities with the packages used and since the environment is very sensitive to these changes, we haven't had much luck with this route. Have you all tried model sharding when you were training or do you have any recommendations on how we should approach this? Thank you for your time and help!

**Comment by jmlee4967** [comment]
Thank you for bringing attention to the project.

Regarding the model training engine, it's worth noting that the current implementation relies on detectron2, which unfortunately lacks support for model sharding. Additionally, there are sections of code related to PyTorch Lightning and Deepspeed, but they have been adopted from OpenFold and have not been actively used or tested within our project.

For managing GPU memory efficiently, you might want to explore mixed precision training. A helpful example configuration file can be found [here](https://github.com/kakaobrain/solvent/blob/main/configs/esm35_evo1_finetune_pdbonly_fp16.yaml).

If you're interested in ESM-based structure prediction, I recommend checking out the OpenFold repository. There, you can explore 'SoloSeq' features, which could prove beneficial for your research. OpenFold, much like our approach, employs sequence cropping during the training phase. However, it goes a step further by supporting longer sequences during the inference phase. 

I hope these information will be helpful for your research!

**Comment by jmlee4967** [comment]
Thank you for bringing this to our attention.
If you have any further questions, please feel free to reopen this issue, and we'll continue to assist you.
Thanks again for your report and collaboration!
