### ISSUE TITLE
How to load existing ESMFold params?

### ISSUE THREAD

**Issue by zouzh14** [kakaobrain/solvent#3]
Dear developers, 

Thanks for providing such a convenient and efficient framework for training the protein folding models. Here I want to load the existing ESMFold model parameters which contains the folding blocks beside embedding layer, for instance, the esmfold_3B_v1.pt from https://dl.fbaipublicfiles.com/fair-esm/models/esmfold_3B_v1.pt. Do you have plan to provide related guide in the future or could give me some suggestions about loading it into solvent?

**Comment by jmlee4967** [comment]
Thank you for your interest in this project.

The goal of Solvent is to allow the design of custom models, both large and small, tailored to the user's needs. Compatibility with weights from ESMFold was not considered during development. Additionally, please note that this project is not actively being developed at the moment, and I'd like to provide a few comments:

- Although the weight keys in Solvent and ESMFold differ, their structural meanings may align. By identifying corresponding keys and adjusting the ESMFold's weight keys accordingly, it may result in successful loading.
- ESMFold_3B_v1 have 48 blocks in the Evoformer, and this should be accounted for in the Solvent configuration to ensure proper loading(ex. NUM_BLOCKS). In the case of using ESM-3B, adjustments to the embedder's configuration(ex. NUM_LAYERS, NUM_HEADS) are also necessary.

I hope the information provided will be beneficial for your research.

**Comment by zouzh14** [comment]
Thanks for your kind suggestions! I will try to deal with it.
