### ISSUE TITLE
pretrained models cannot be loaded

### ISSUE THREAD

**Issue by czhs** [kakaobrain/solvent#4]
Thank you for creating such a useful project!

**Problem Description**
I am having trouble running the inference and evaluation scripts. For the demo command, the directories pointing to the .yml and .pt files did not exist. Why is the command written that way? 

Instead, I used the provided .yml file in the config folder, and I used the downloaded model weights from the pretrained_weights folder. When running, I had an error that seems to indicate that the weight files downloaded are incorrect. I suspect the error occurs because not all of the weights can be found, and so there are some None type objects being passed around. Thank you so much for your help!

**Environment Config**
From pip list, here are the libraries I have downloaded.
[env_lib.txt](https://github.com/kakaobrain/solvent/files/14325273/env_lib.txt)

Note that I downloaded xformers v0.0.20 since the most recent xformers no longer is compatible.
I am using an NVIDIA RTX 4090, and cuda toolkit 11.3. I have tried using both cuda toolkits 11.8 and 11.3
My Ubuntu version is 20.04

**Command Ran and Errors**
This is the command I ran
`python demo/demo.py \
    --config-file /home/hshi/Desktop/solvent/configs/esm35_evo1_finetune_pdbonly.yaml \
    --input datasets/cameo/fasta_dir/7b8b_A.fasta \
    --output output/esm35_evo1/finetune_pdbonly/results \
    --opt \
    SOLVER.SEQ_PER_BATCH 1 \
    MODEL.WEIGHTS /home/hshi/Desktop/solvent/pretrained_model/esm2_t12_35M_UR50D.pt`

Here was the output of the command:
[error_from_command.txt](https://github.com/kakaobrain/solvent/files/14337614/error_from_command.txt)

**Comment by jmlee4967** [comment]
We are pleased that you are utilizing this project.

Regarding the pretrained model, I will provide a response as follows:
- Currently, we do not provide trained weights for structure prediction.
- Upon completing the training process, users will acquire an `output` folder. The demo command examples are crafted based on this folder. 
- The `pretrained_model` folder located in the project root refers to the pretrained weights of the Protein Language Model(PLM), and it is not for Folding pretrained weights. We only provide a download guide for the PLM pretrained model, which is necessary for training the folding model.
  
Furthermore, the recent update to xformer has caused a mismatch with Solvent. Thank you for bringing this to our attention. Solvent has been tested with xformer version 0.0.21, and it can be installed exactly as follows:
`pip install -v -U git+https://github.com/facebookresearch/xformers.git@b31f4a1#egg=xformers`

I hope the information provided will be beneficial for your research!

**Comment by czhs** [comment]
Hi, thank you for your advice! I found the issue: biotite 0.36.1 requires  python >= 3.9. and the error goes away once you use python 3.9 instead of 3.8 (as listed in the dependencies). I also switched to a NVIDIA 3080 GPU, but I'm not sure that was the issue.
