### ISSUE TITLE
Ouput is unrelaxed, does not have meaningful prediction

### ISSUE THREAD

**Issue by czhs** [kakaobrain/solvent#6]
Hi, thank you for your help previously.

I am having trouble with the outputs of the models, they all are all marked as unrelaxed. how do i predict/access the full structures?

**Comment by jmlee4967** [comment]
Thank you for reaching out!

The primary focus of this project is to reproduce ESMFold and extend its functionalities. Relaxation is not part of the ESMFold process; hence, it's not incorporated into this project. Moreover, it's known that including relaxation in ESMFold doesn't contribute to performance enhancement([facebookresearch/esm#415](https://github.com/facebookresearch/esm/discussions/415)).  
If you're seeking relaxed structures in the predicted output, you might want to explore the modules used in Alphafold2([https://github.com/google-deepmind/alphafold/tree/main/alphafold/relax](https://github.com/google-deepmind/alphafold/tree/main/alphafold/relax)).

I hope my response is helpful.

**Comment by czhs** [comment]
Hi! Thanks for the clarification.

I also ran the model with Omegafold, and it also gave unrelaxed structures. Does this project allow for structure prediction where I can do TMscore comparisons with other proteins (eg replace completely my use of omega fold with solvent)? If so, how do I get an actual protein structure prediction using solvent?

Current prediction output:
![Screenshot from 2024-03-03 21-46-47](https://github.com/kakaobrain/solvent/assets/83367088/c87a67ba-9dd9-47ee-909a-63d09890db73)


Thanks for you help!

**Comment by jmlee4967** [comment]
I may have provided an incomplete explanation.

If you've completed training and used the weights to run a demo, you should be able to obtain predicted structure PDB files. With these PDB files, you can calculate TMscore against other PDB files. As mentioned above, you can transform these files into relaxed output using external module.

After looking at the figure above, it seems more like a case of the model not being trained correctly rather than a relaxation issue.

**Comment by czhs** [comment]
You are right, this is not an issue with relaxation, thank you for the clarification. I tried running the demo straight from the downloaded weights provided in the download instructions page. Do I need to train the downloaded ESM 650 weights using solvent before I run the demo?

**Comment by jmlee4967** [comment]
Yes, you're correct. 
Before running the demo, it's essential to train the structure prediction (folding) model based on the protein language model(ex. esm).

**Comment by czhs** [comment]
Okay that makes so much sense, thank you so much. Would it be possible for you to provide a download link for some solvent-trained weights for people who just want to run the demo?
